encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("searched/", views.searchentry, name="searchentry"),
    path("createnew/", views.createnew, name="createnew"),
    path("createdpage/", views.createdpage, name="createdpage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/views.py
import markdown2
from django.shortcuts import render
from django import forms
from . import util

class SearchEntryForm(forms.Form):
    entry_searched = forms.CharField(label = "")

class CreatePageForm(forms.Form):
    title = forms.CharField(label = "Title")
    content = forms.CharField(widget=forms.Textarea(), label = "Markdown content for the page")

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form" : SearchEntryForm()
    })

def entry(request, entry):
    if entry in util.list_entries():
        return render(request, "encyclopedia/entries.html",{
            "entry": markdown2.markdown(util.get_entry(f"{entry}")),
            "form" : SearchEntryForm()
            })
    else:
        return render(request, "encyclopedia/error.html", {
            "form" : SearchEntryForm(),
            "exists": False
            })

def searchentry(request):
    if request.method == "POST":
        entry = SearchEntryForm(request.POST)
        if entry.is_valid():
            searched = entry.cleaned_data['entry_searched']
            if searched in util.list_entries():
                return render(request, "encyclopedia/entries.html",{
                    "entry": markdown2.markdown(util.get_entry(f"{searched}")),
                    "form" : SearchEntryForm()
                    })
            else:
                results = []
                for i in range(len(util.list_entries())):
                    if searched in util.list_entries()[i]:
                        results.append(util.list_entries()[i])
                return render(request, "encyclopedia/searchresults.html", {
                    "results": results,
                    "form" : SearchEntryForm()
                })

    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "form" : SearchEntryForm()
        })

def createnew(request):
    return render(request, "encyclopedia/createnew.html", {
        "form" : SearchEntryForm(),
        "title": CreatePageForm()
        })

def createdpage(request):
    if request.method == "POST":
        page = CreatePageForm(request.POST)
        if page.is_valid():
            title = page.cleaned_data['title']
            if title in util.list_entries():
                return render(request, "encyclopedia/error.html", {
                    "form" : SearchEntryForm(),
                    "exists": True
                    })
            content = page.cleaned_data['content']
            util.save_entry(title, content)

        return render(request, "encyclopedia/entries.html",{
            "entry": markdown2.markdown(util.get_entry(f"{title}")),
            "form" : SearchEntryForm()
            })

encyclopedia/templates/encyclopedia/createnew.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}
    <br>
{% block body %}
     <h1>Create New page</h1>

     <form method = "post" action=" {% url 'encyclopedia:createdpage'%}" >
         {% csrf_token %}
         {{ title }}
         {{ content }}
     <input type="submit" style name="Save Page" value="Save Page">
     </form>

     <!-- <textarea id="text" name="Input Markdown content for new page" rows="8" cols="80"></textarea> -->

{% endblock %}

encyclopedia/templates/encyclopedia/entries.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ entryname }}</h1>

     {{ entry }}
        <!-- {% for entry in entries %}
            <li>{{ entry }}</li>
        {% endfor %} -->


{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Error Page</h1>

    {% if not exists%}
        <p>The page that you try to visit does not exist. </p>
    {% else %}
        <p>The page that you try to make already exists. </p>
    {% endif  %}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

<!-- {% block form%}
    <form action = "">
        {% csrf_token %}
        <!-- <input class="search" type="text" name = "q" placeholder="Search Encyclopedia"> -->
        <!-- {{ form }}
    </form>
{% endblock %} -->

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:entry' entry=entry%}">{{entry}}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method = "post" action="{% url 'encyclopedia:searchentry'%}">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:createnew' %}">Create New Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    </body>
</html>

encyclopedia/templates/encyclopedia/searchentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
     {{ entry|safe }}
{% endblock %}

encyclopedia/templates/encyclopedia/searchresults.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in results %}
            <li>
                <a href="{% url 'encyclopedia:entry' entry=entry %}">{{entry}}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}